const en = {
  nav: {
    about: "About",
    skills: "Skills",
    experience: "Experience",
    projects: "Projects",
    contact: "Contact",
    cv: "Resume",
  },
  hero: {
    status: "Currently interning at CBX Groupe · Seeking work-study Sept. 2026",
    title1: "Younes",
    title2: "Matoub",
    subtitle: "Full-Stack & Mobile Developer · L3 Computer Science · University of Lille",
    description:
      "Currently a full-stack development intern at CBX Groupe (BMA IT), I'm looking for a **work-study Master's position starting September 2026**. Passionate about building robust web, mobile and software applications that actually get used.",
    cta_contact: "Get in touch",
    cta_projects: "View my projects",
    mobility: "📍 Mobile: Lille Métropole & Île-de-France",
    card: {
      status_label: "STATUS",
      status_value: "Interning · Open to work-study",
      fields: [
        { label: "EDUCATION", value: "L3 CS · University of Lille" },
        { label: "CURRENT ROLE", value: "Full-Stack Intern · CBX Groupe" },
        { label: "LOOKING FOR", value: "Work-study Master · from Sept. 2026" },
      ],
      languages_label: "LANGUAGES",
    },
  },
  skills: {
    section_label: "// technical skills",
    title: "My Stack",
    groups: [
      {
        label: "Backend",
        skills: ["Java · Spring Boot", "Symfony · PHP 8", "Node.js · Express", "REST API"],
      },
      {
        label: "Frontend",
        skills: ["React · React 19", "React Native", "Angular", "HTML · CSS · JavaScript"],
      },
      {
        label: "Mobile",
        skills: ["React Native", "Flutter · Dart", "Firebase"],
      },
      {
        label: "Databases",
        skills: ["MySQL · SQL", "PostgreSQL", "MongoDB · Firebase"],
      },
      {
        label: "DevOps & Tools",
        skills: ["Docker · Docker Compose", "Jenkins · ArgoCD", "Git · GitHub", "Maven"],
      },
      {
        label: "Methodology",
        skills: ["UML · Merise", "OOP · SOLID", "Design Patterns", "Technical documentation"],
      },
    ],
    languages_title: "Languages",
    tools_title: "Tools",
    languages: [
      { lang: "French", level: "C1 (TCF)", color: "#c2622a" },
      { lang: "English", level: "B2 Advanced", color: "#8b4513" },
      { lang: "Kabyle", level: "Native", color: "#d4842e" },
      { lang: "Arabic", level: "Fluent", color: "#a06030" },
    ],
  },
  experience: {
    section_label: "// professional experience",
    title: "My internships",
    items: [
      {
        id: 1,
        company: "CBX Groupe · BMA IT",
        role: "Full-Stack Developer Intern",
        period: "April 2026 – July 2026",
        location: "Massy (91) · France",
        status: "Ongoing",
        description: "4-month internship at CBX Groupe, a digital HR platform publisher (Galaxy Jobs and TimeManager).",
        highlights: [
          "Development of the Galaxy Jobs mobile app in React Native",
          "Development of the web interface in Angular",
          "Frontend and Backend contributions (Spring Boot) on feature evolution",
          "Integration of AI-based features to enhance application value",
          "CI/CD environment: Jenkins, ArgoCD, Git",
        ],
        stack: ["React Native", "Angular", "Spring Boot", "Java", "Jenkins", "ArgoCD", "Git"],
        color: "#c2622a",
      },
      {
        id: 2,
        company: "Amazigh Language & Culture Research Center",
        role: "Web Developer Intern",
        period: "September 2023 – March 2024",
        location: "Béjaïa · Algeria",
        status: "Completed",
        description: "Design and development of Wiki-Zed, a Wikipedia-like collaborative web platform dedicated to the Amazigh world (language, culture, history), with an editorial validation workflow.",
        highlights: [
          "Functional design and requirements specification writing",
          "Database modeling and platform architecture",
          "Full-stack development with HTML, CSS, JavaScript, PHP and SQL",
          "Editorial workflow implementation (submission, review, publication)",
          "Multi-role management (contributor, reviewer, reader)",
        ],
        stack: ["HTML", "CSS", "JavaScript", "PHP", "SQL", "MySQL"],
        color: "#8b4513",
      },
    ],
  },
  projects: {
    section_label: "// personal & academic projects",
    title: "What I've built",
    github_cta: "GitHub",
    see_code: "View source",
    items: [
      {
        id: 1,
        title: "TMDB Explorer",
        category: "Fullstack",
        period: "February 2026",
        image: "/projects/tmdb.png",
        stack: ["Symfony", "React 19", "Docker", "PHP 8.4", "REST API"],
        description: "Web app displaying top-rated movies and TV shows via the TMDB v3 API. Fully containerized, secured REST API.",
        highlights: [
          "Symfony REST API (Controller + Service layers)",
          "React 19 with Router 7 and pagination",
          "Full Docker Compose setup",
          "Security: CORS + environment variable API key",
        ],
        github: "https://github.com/youyou-dev4/tmdb-symfony-react",
        color: "#c2622a",
        icon: "🎬",
      },
      {
        id: 2,
        title: "Bladiway – Carpooling",
        category: "Mobile & Web",
        period: "Feb – Jun 2025",
        image: "/projects/covoiturage.jpg",
        stack: ["Flutter", "Firebase", "React", "Firestore", "Cloud Messaging"],
        description: "Full carpooling solution with a cross-platform mobile app and a web admin back-office. Bachelor's final project in team.",
        highlights: [
          "Flutter app: auth, map, trips, real-time messaging",
          "Push notifications with Firebase Cloud Messaging",
          "Multilingual support (FR, EN, Tamazight, AR)",
          "React admin back-office: user management, document verification",
        ],
        github: "https://github.com/Sofiane-Meziane/Bladiway",
        color: "#8b4513",
        icon: "🚗",
      },
      {
        id: 3,
        title: "Bike-sharing System",
        category: "Backend & Architecture",
        period: "Oct – Dec 2025",
        image: "/projects/velos.jpg",
        stack: ["Java", "Maven", "JUnit 5", "Design Patterns", "UML"],
        description: "Object-oriented design of a robust bike rental system applying SOLID principles and design patterns.",
        highlights: [
          "SOLID principles applied throughout",
          "Design patterns (Strategy, Observer…)",
          "JUnit 5 unit testing",
          "Full UML documentation",
        ],
        github: "https://github.com/youyou-dev4/Velos-libre-service",
        color: "#d4842e",
        icon: "🚲",
      },
      {
        id: 4,
        title: "Driving School Software",
        category: "Desktop",
        period: "Oct 2024 – Jan 2025",
        image: "/projects/autoecole.jpg",
        stack: ["Java", "JavaFX", "SQL", "MVC"],
        description: "Full desktop management software: students, scheduling, instructors, and accounting.",
        highlights: [
          "MVC architecture",
          "SQL database management",
          "UML design (Use cases, Sequences)",
          "Integrated accounting module",
        ],
        github: "https://github.com/youyou-dev4/autoEcole",
        color: "#a06030",
        icon: "🚘",
      },
    ],
  },
  education: {
    section_label: "// education",
    title: "Degrees",
    items: [
      { year: "2025 →", title: "L3 Computer Science", school: "University of Lille", note: "In progress" },
      { year: "2025", title: "Bachelor's in Computer Science", school: "University of Béjaïa, Algeria", note: "Good standing" },
      { year: "2022", title: "Baccalauréat – Experimental Sciences", school: "Algeria", note: "With honors" },
    ],
  },
  contact: {
    section_label: "// contact",
    title: "Let's talk 👋",
    subtitle: "I'm looking for a work-study Master's position starting September 2026, in web, mobile or software development.\nMobile across the Lille metropolitan area and Île-de-France. Feel free to reach out!",
    download_cv: "Download my Resume",
    footer: "© 2026 · Younes Matoub · React Portfolio",
  },
};

export default en;