const en = {
  nav: {
    about: "About",
    skills: "Skills",
    projects: "Projects",
    contact: "Contact",
    cv: "Resume",
  },
  hero: {
    status: "Available from April 13, 2026",
    title1: "Younes",
    title2: "Matoub",
    subtitle: "Full-Stack & Mobile Developer · L3 Computer Science · University of Lille",
    description:
      "Passionate about building robust systems and high-performance applications. Looking for a minimum 3-month internship, then a work-study Master's degree to keep growing alongside experienced teams.",
    cta_contact: "Get in touch",
    cta_projects: "View my projects",
    card: {
      status_label: "STATUS",
      status_value: "Available",
      fields: [
        { label: "EDUCATION", value: "L3 CS · University of Lille" },
        { label: "LOCATION", value: "Villeneuve D'Ascq, 59" },
        { label: "LOOKING FOR", value: "Internship 3mo+ · from April 2026" },
        { label: "GOAL", value: "Work-study Master's degree" },
      ],
      languages_label: "LANGUAGES",
    },
  },
  skills: {
    section_label: "// technical skills",
    title: "My Stack",
    groups: [
      {
        label: "Backend",
        skills: ["Java · SOLID · JUnit", "Symfony · PHP", "Node.js · Express", "REST API"],
      },
      {
        label: "Frontend",
        skills: ["React", "HTML · CSS", "JavaScript", "VueJS"],
      },
      {
        label: "Mobile",
        skills: ["Flutter · Dart", "Firebase"],
      },
      {
        label: "Databases",
        skills: ["MySQL · SQL", "PostgreSQL", "MongoDB · NoSQL"],
      },
      {
        label: "DevOps & Tools",
        skills: ["Docker · Docker Compose", "Git · GitHub", "Maven"],
      },
      {
        label: "Methodology",
        skills: ["UML · Merise", "OOP · SOLID", "Unit testing", "Technical documentation"],
      },
    ],
    languages_title: "Languages",
    tools_title: "Tools",
    languages: [
      { lang: "French", level: "C1 Expert", color: "#00ff88" },
      { lang: "English", level: "B2 Advanced", color: "#4f9eff" },
      { lang: "Kabyle", level: "Native", color: "#ff9f43" },
      { lang: "Arabic", level: "Fluent", color: "#a29bfe" },
    ],
  },
  projects: {
    section_label: "// projects & experience",
    title: "What I've built",
    github_cta: "GitHub",
    see_code: "View source",
    items: [
      {
        id: 1,
        title: "TMDB Explorer",
        category: "Fullstack",
        period: "2025",
        image: "/projects/tmdb.png",
        stack: ["Symfony 8", "React 19", "Docker", "PHP 8.4", "REST API"],
        description: "Web app displaying top-rated movies and TV shows via the TMDB v3 API. Fully containerized, secured REST API.",
        highlights: [
          "Symfony REST API (Controller + Service layers)",
          "React 19 with Router 7 and pagination",
          "Full Docker Compose setup",
          "Security: CORS + environment variable API key",
        ],
        github: "https://github.com/youyou-dev4/tmdb-symfony-react",
        color: "#00ff88",
        icon: "🎬",
      },
      {
        id: 2,
        title: "Carpooling App",
        category: "Mobile & Web",
        period: "Feb – Jun 2025",
        image: "/projects/covoiturage.jpg",
        stack: ["Flutter", "Firebase", "React", "UML"],
        description: "Full carpooling solution with a cross-platform mobile app and a web admin dashboard.",
        highlights: [
          "Firebase NoSQL architecture",
          "Cross-platform Flutter mobile app",
          "React admin dashboard",
          "Functional tests & performance optimization",
        ],
        github: "https://github.com/Sofiane-Meziane/Bladiway",
        color: "#4f9eff",
        icon: "🚗",
      },
      {
        id: 3,
        title: "Bike-sharing System",
        category: "Backend & Architecture",
        period: "Oct – Dec 2025",
        image: "/projects/velos.jpg",
        stack: ["Java", "Maven", "JUnit 5", "Design Patterns", "UML"],
        description: "Object-oriented design of a robust bike rental system applying SOLID principles.",
        highlights: [
          "SOLID principles applied throughout",
          "Design patterns (Strategy, Observer…)",
          "JUnit 5 unit testing",
          "Full UML documentation",
        ],
        github: "https://github.com/youyou-dev4/Velos-libre-service",
        color: "#ff9f43",
        icon: "🚲",
      },
      {
        id: 4,
        title: "Driving School Software",
        category: "Desktop",
        period: "Oct 2024 – Jan 2025",
        image: "/projects/autoecole.jpg",
        stack: ["Java", "JavaFX", "SQL", "MVC"],
        description: "Full desktop management software: students, scheduling, instructors, and accounting.",
        highlights: [
          "MVC architecture",
          "SQL database management",
          "UML design (Use cases, Sequences)",
          "Integrated accounting module",
        ],
        github: "https://github.com/youyou-dev4/autoEcole",
        color: "#a29bfe",
        icon: "🚘",
      },
      {
        id: 5,
        title: "Amazigh Web Platform",
        category: "Fullstack Web · Internship",
        period: "Sep 2023 – Mar 2024",
        image: "/projects/amazighe.jpg",
        stack: ["HTML/CSS", "PHP", "JavaScript", "SQL"],
        description: "Internship at the Amazigh Language & Culture Research Center. Full-stack web platform development.",
        highlights: [
          "Requirements specification writing",
          "Fullstack PHP/SQL development",
          "Code refactoring & optimization",
          "Debugging and testing",
        ],
        github: "https://github.com/youyou-dev4/WikiZed",
        color: "#fd79a8",
        icon: "🌐",
      },
    ],
  },
  education: {
    section_label: "// education",
    title: "Degrees",
    items: [
      { year: "2025 →", title: "L3 Computer Science", school: "University of Lille", note: "In progress" },
      { year: "2025", title: "Bachelor's in Computer Science", school: "University of Béjaïa, Algeria", note: "Good standing" },
      { year: "2022", title: "Baccalauréat – Experimental Sciences", school: "Algeria", note: "With honors" },
    ],
  },
  contact: {
    section_label: "// contact",
    title: "Let's talk 👋",
    subtitle: "I'm looking for a 3-month+ internship starting April 2026, then a work-study Master's.\nFeel free to reach out!",
    download_cv: "Download my Resume",
    footer: "© 2026 · Younes Matoub · React Portfolio",
  },
};

export default en;
