const fr = {
  nav: {
    about: "À propos",
    skills: "Compétences",
    experience: "Expérience",
    projects: "Projets",
    contact: "Contact",
    cv: "CV",
  },
  hero: {
    status: "En stage chez CBX Groupe · Recherche alternance Sept. 2026",
    title1: "Younes",
    title2: "Matoub",
    subtitle: "Développeur Full-Stack & Mobile · L3 Informatique · Université de Lille",
    description:
      "Actuellement stagiaire développeur full-stack chez CBX Groupe (BMA IT), je recherche une **alternance en Master à partir de septembre 2026**. Passionné par le développement d'applications web, mobiles et logicielles, j'aime concevoir des produits robustes et utiles.",
    cta_contact: "Me contacter",
    cta_projects: "Voir mes projets",
    mobility: "📍 Mobile : Métropole Lilloise & Île-de-France",
    card: {
      status_label: "STATUT",
      status_value: "En stage · Recherche alternance",
      fields: [
        { label: "FORMATION", value: "L3 Info · Université de Lille" },
        { label: "EN POSTE", value: "Stagiaire Full-Stack · CBX Groupe" },
        { label: "RECHERCHE", value: "Alternance Master · dès Sept. 2026" },
      ],
      languages_label: "LANGUES",
    },
  },
  skills: {
    section_label: "// compétences techniques",
    title: "Ma Stack",
    groups: [
      {
        label: "Backend",
        skills: ["Java · Spring Boot", "Symfony · PHP 8", "Node.js · Express", "API REST"],
      },
      {
        label: "Frontend",
        skills: ["React · React 19", "React Native", "Angular", "HTML · CSS · JavaScript"],
      },
      {
        label: "Mobile",
        skills: ["React Native", "Flutter · Dart", "Firebase"],
      },
      {
        label: "Base de données",
        skills: ["MySQL · SQL", "PostgreSQL", "MongoDB · Firebase"],
      },
      {
        label: "DevOps & Outils",
        skills: ["Docker · Docker Compose", "Jenkins · ArgoCD", "Git · GitHub", "Maven"],
      },
      {
        label: "Méthodes",
        skills: ["UML · Merise", "POO · SOLID", "Design Patterns", "Documentation technique"],
      },
    ],
    languages_title: "Langues",
    tools_title: "Outils",
    languages: [
      { lang: "Français", level: "C1 (TCF)", color: "#c2622a" },
      { lang: "Anglais", level: "B2 Avancé", color: "#8b4513" },
      { lang: "Kabyle", level: "Natif", color: "#d4842e" },
      { lang: "Arabe", level: "Courant", color: "#a06030" },
    ],
  },
  experience: {
    section_label: "// expérience professionnelle",
    title: "Mes stages",
    items: [
      {
        id: 1,
        company: "CBX Groupe · BMA IT",
        role: "Stagiaire Développeur Full-Stack",
        period: "Avril 2026 – Juillet 2026",
        location: "Massy (91) · France",
        status: "En cours",
        description: "Stage de 4 mois au sein de CBX Groupe, éditeur de plateformes digitales RH (Galaxy Jobs et TimeManager).",
        highlights: [
          "Développement de l'application mobile Galaxy Jobs en React Native",
          "Développement de la partie web en Angular",
          "Contributions Frontend et Backend (Spring Boot) sur les évolutions fonctionnelles",
          "Intégration de fonctionnalités basées sur l'IA pour augmenter la valeur des applications",
          "Environnement CI/CD : Jenkins, ArgoCD, Git",
        ],
        stack: ["React Native", "Angular", "Spring Boot", "Java", "Jenkins", "ArgoCD", "Git"],
        color: "#c2622a",
      },
      {
        id: 2,
        company: "Centre de Recherche en Langue et Culture Amazighes",
        role: "Stagiaire Développeur Web",
        period: "Septembre 2023 – Mars 2024",
        location: "Béjaïa · Algérie",
        status: "Terminé",
        description: "Conception et développement de Wiki-Zed, une plateforme web collaborative type Wikipédia dédiée au monde amazigh (langue, culture, histoire), avec workflow éditorial de validation.",
        highlights: [
          "Conception fonctionnelle et rédaction du cahier des charges",
          "Modélisation de la base de données et architecture de la plateforme",
          "Développement full-stack avec HTML, CSS, JavaScript, PHP et SQL",
          "Implémentation du workflow éditorial (soumission, relecture, publication)",
          "Gestion multi-rôles (contributeur, réviseur, lecteur)",
        ],
        stack: ["HTML", "CSS", "JavaScript", "PHP", "SQL", "MySQL"],
        color: "#8b4513",
      },
    ],
  },
  projects: {
    section_label: "// projets personnels & académiques",
    title: "Ce que j'ai construit",
    github_cta: "GitHub",
    see_code: "Voir le code",
    items: [
      {
        id: 1,
        title: "TMDB Explorer",
        category: "Fullstack",
        period: "Février 2026",
        image: "/projects/tmdb.png",
        stack: ["Symfony", "React 19", "Docker", "PHP 8.4", "REST API"],
        description: "Application web affichant les films et séries les mieux notés via l'API TMDB v3. Architecture conteneurisée, API REST sécurisée.",
        highlights: [
          "API REST Symfony (Controller + Service)",
          "React 19 avec Router 7 et pagination",
          "Docker Compose complet",
          "Sécurité : CORS + variable d'environnement",
        ],
        github: "https://github.com/youyou-dev4/tmdb-symfony-react",
        color: "#c2622a",
        icon: "🎬",
      },
      {
        id: 2,
        title: "Bladiway – Covoiturage",
        category: "Mobile & Web",
        period: "Fév – Juin 2025",
        image: "/projects/covoiturage.jpg",
        stack: ["Flutter", "Firebase", "React", "Firestore", "Cloud Messaging"],
        description: "Solution complète de covoiturage avec app mobile cross-platform et back-office web d'administration. Projet de fin de Licence en équipe.",
        highlights: [
          "App Flutter : authentification, carte, trajets, messagerie temps réel",
          "Notifications push Firebase Cloud Messaging",
          "Support multilingue (FR, EN, Tamazight, AR)",
          "Back-office React : gestion utilisateurs, vérification documents",
        ],
        github: "https://github.com/Sofiane-Meziane/Bladiway",
        color: "#8b4513",
        icon: "🚗",
      },
      {
        id: 3,
        title: "Système Vélos Libre-service",
        category: "Backend & Architecture",
        period: "Oct – Déc 2025",
        image: "/projects/velos.jpg",
        stack: ["Java", "Maven", "JUnit 5", "Design Patterns", "UML"],
        description: "Conception orientée objet d'un système de location de vélos robuste avec principes SOLID et design patterns.",
        highlights: [
          "Principes SOLID appliqués",
          "Design patterns (Strategy, Observer…)",
          "Tests unitaires JUnit 5",
          "Documentation UML complète",
        ],
        github: "https://github.com/youyou-dev4/Velos-libre-service",
        color: "#d4842e",
        icon: "🚲",
      },
      {
        id: 4,
        title: "Logiciel Auto-école",
        category: "Desktop",
        period: "Oct 2024 – Jan 2025",
        image: "/projects/autoecole.jpg",
        stack: ["Java", "JavaFX", "SQL", "MVC"],
        description: "Logiciel desktop complet : gestion des élèves, planning, moniteurs et comptabilité.",
        highlights: [
          "Architecture MVC",
          "Gestion base de données SQL",
          "Conception UML (Use cases, Séquences)",
          "Module comptabilité intégré",
        ],
        github: "https://github.com/youyou-dev4/autoEcole",
        color: "#a06030",
        icon: "🚘",
      },
    ],
  },
  education: {
    section_label: "// formation",
    title: "Diplômes",
    items: [
      { year: "2025 →", title: "L3 Informatique", school: "Université de Lille", note: "En cours" },
      { year: "2025", title: "Licence Informatique", school: "Université de Béjaïa, Algérie", note: "Mention Assez Bien" },
      { year: "2022", title: "Baccalauréat Sciences Expérimentales", school: "Algérie", note: "Mention Bien" },
    ],
  },
  contact: {
    section_label: "// contact",
    title: "Parlons-en 👋",
    subtitle: "Je recherche une alternance en Master à partir de septembre 2026, en développement web, mobile ou logiciel.\nMobile sur la métropole lilloise et en Île-de-France. N'hésitez pas à me contacter !",
    download_cv: "Télécharger mon CV",
    footer: "© 2026 · Younes Matoub · Portfolio React",
  },
};

export default fr;