const fr = {
  nav: {
    about: "À propos",
    skills: "Compétences",
    projects: "Projets",
    contact: "Contact",
    cv: "CV",
  },
  hero: {
    status: "Disponible dès le 13 avril 2026",
    title1: "Younes",
    title2: "Matoub",
    subtitle: "Développeur Full-Stack & Mobile · L3 Informatique · Université de Lille",
    description:
      "Passionné par la conception de systèmes robustes et d'applications performantes. À la recherche d'un stage de minimum 3 mois, puis d'un Master en alternance pour continuer à grandir aux côtés d'équipes expertes.",
    cta_contact: "Me contacter",
    cta_projects: "Voir mes projets",
    card: {
      status_label: "STATUT",
      status_value: "Disponible",
      fields: [
        { label: "FORMATION", value: "L3 Info · Université de Lille" },
        { label: "LOCALISATION", value: "Villeneuve D'Ascq, 59" },
        { label: "RECHERCHE", value: "Stage 3 mois min. · dès Avril 2026" },
        { label: "OBJECTIF", value: "Master en alternance" },
      ],
      languages_label: "LANGUES",
    },
  },
  skills: {
    section_label: "// compétences techniques",
    title: "Ma Stack",
    groups: [
      {
        label: "Backend",
        skills: ["Java · SOLID · JUnit", "Symfony · PHP 8", "Node.js · Express", "API REST"],
      },
      {
        label: "Frontend",
        skills: ["React", "HTML · CSS", "JavaScript", "VueJS"],
      },
      {
        label: "Mobile",
        skills: ["Flutter · Dart", "Firebase"],
      },
      {
        label: "Base de données",
        skills: ["MySQL · SQL", "PostgreSQL", "MongoDB · NoSQL"],
      },
      {
        label: "DevOps & Outils",
        skills: ["Docker · Docker Compose", "Git · GitHub", "Maven"],
      },
      {
        label: "Méthodes",
        skills: ["UML · Merise", "POO · SOLID", "Tests unitaires", "Documentation technique"],
      },
    ],
    languages_title: "Langues",
    tools_title: "Outils",
    languages: [
      { lang: "Français", level: "C1 Expert", color: "#00ff88" },
      { lang: "Anglais", level: "B2 Avancé", color: "#4f9eff" },
      { lang: "Kabyle", level: "Natif", color: "#ff9f43" },
      { lang: "Arabe", level: "Courant", color: "#a29bfe" },
    ],
  },
  projects: {
    section_label: "// projets & expériences",
    title: "Ce que j'ai construit",
    github_cta: "GitHub",
    see_code: "Voir le code",
    items: [
      {
        id: 1,
        title: "TMDB Explorer",
        category: "Fullstack",
        period: "2025",
        image: "/projects/tmdb.png",
        stack: ["Symfony 8", "React 19", "Docker", "PHP 8.4", "REST API"],
        description: "Application web affichant les films et séries les mieux notés via l'API TMDB v3. Architecture conteneurisée, API REST sécurisée.",
        highlights: [
          "API REST Symfony (Controller + Service)",
          "React 19 avec Router 7 et pagination",
          "Docker Compose complet",
          "Sécurité : CORS + variable d'environnement",
        ],
        github: "https://github.com/youyou-dev4/tmdb-symfony-react",
        color: "#00ff88",
        icon: "🎬",
      },
      {
        id: 2,
        title: "Application de Covoiturage",
        category: "Mobile & Web",
        period: "Fév – Juin 2025",
        image: "/projects/covoiturage.jpg",
        stack: ["Flutter", "Firebase", "React", "UML"],
        description: "Solution complète de covoiturage avec app mobile cross-platform et dashboard administrateur web.",
        highlights: [
          "Architecture Firebase NoSQL",
          "App Flutter cross-platform",
          "Dashboard admin React",
          "Tests fonctionnels & optimisation",
        ],
        github: "https://github.com/Sofiane-Meziane/Bladiway",
        color: "#4f9eff",
        icon: "🚗",
      },
      {
        id: 3,
        title: "Système Vélos Libre-service",
        category: "Backend & Architecture",
        period: "Oct – Déc 2025",
        image: "/projects/velos.jpg",
        stack: ["Java", "Maven", "JUnit 5", "Design Patterns", "UML"],
        description: "Conception orientée objet d'un système de location de vélos robuste avec principes SOLID.",
        highlights: [
          "Principes SOLID appliqués",
          "Design patterns (Strategy, Observer…)",
          "Tests unitaires JUnit 5",
          "Documentation UML complète",
        ],
        github: "https://github.com/youyou-dev4/Velos-libre-service",
        color: "#ff9f43",
        icon: "🚲",
      },
      {
        id: 4,
        title: "Logiciel Auto-école",
        category: "Desktop",
        period: "Oct 2024 – Jan 2025",
        image: "/projects/autoecole.jpg",
        stack: ["Java", "JavaFX", "SQL", "MVC"],
        description: "Logiciel desktop complet : gestion des élèves, planning, moniteurs et comptabilité.",
        highlights: [
          "Architecture MVC",
          "Gestion base de données SQL",
          "Conception UML (Use cases, Séquences)",
          "Module comptabilité intégré",
        ],
        github: "https://github.com/youyou-dev4/autoEcole",
        color: "#a29bfe",
        icon: "🚘",
      },
      {
        id: 5,
        title: "Plateforme Web Amazighe",
        category: "Fullstack Web · Stage",
        period: "Sept 2023 – Mars 2024",
        image: "/projects/amazighe.jpg",
        stack: ["HTML/CSS", "PHP", "JavaScript", "SQL"],
        description: "Stage au Centre de recherche en langue amazighe. Développement complet d'une plateforme web.",
        highlights: [
          "Rédaction cahier des charges",
          "Développement Fullstack PHP/SQL",
          "Refactoring et optimisation",
          "Débogage et tests",
        ],
        github: "https://github.com/youyou-dev4/WikiZed",
        color: "#fd79a8",
        icon: "🌐",
      },
    ],
  },
  education: {
    section_label: "// formation",
    title: "Diplômes",
    items: [
      { year: "2025 →", title: "L3 Informatique", school: "Université de Lille", note: "En cours" },
      { year: "2025", title: "Licence Informatique", school: "Université de Béjaïa, Algérie", note: "Mention Assez Bien" },
      { year: "2022", title: "Baccalauréat Sciences Expérimentales", school: "Algérie", note: "Mention Bien" },
    ],
  },
  contact: {
    section_label: "// contact",
    title: "Parlons-en 👋",
    subtitle: "Je recherche un stage de minimum 3 mois à partir d'avril 2026, puis un Master en alternance.\nN'hésitez pas à me contacter !",
    download_cv: "Télécharger mon CV",
    footer: "© 2026 · Younes Matoub · Portfolio React",
  },
};

export default fr;
